BINANCE_API_KEY = "DnwcF34Sg2QaRcTskn9L35zudW3hXITkIpp47FXvMRzPeay49i9BmypRBod5xFlf"
BINANCE_SECRET_KEY = "DA1apmOA9jzvR1NoeAtdFeQRtb5f7lu8pGEKyiiT8jH9QLGRF2G6b218HmQtLbmu"

BYBIT_API_KEY = "HrZH0ZeUa1wRBrFmwx"
BYBIT_SECRET_KEY = "OsyhuUE6vf7gfMhHBkcYbcAKOmtPz0044QmX"

BYBIT_TESTNET_API_KEY = "11LdsbdGURmGJdb447"
BYBIT_TESTNET_SECRET_KEY = "jlAj5OjSGloDSsMDiyw5FddXMuF14EgsZXIN"

URL_API_BYBIT_TESTNET = 'https://api-testnet.bybit.com'
URL_API_BYBIT = 'https://api.bybit.com'
